<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Irihi.Mirana.Themes.TDesign</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Irihi.Mirana\Irihi.Mirana.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
