<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Irihi.Mafia.Themes.TDesign</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Irihi.Iconica.TDesign" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Irihi.Mafia\Irihi.Mafia.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
