<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>Irihi.Mafia.Themes.TDesign</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Irihi.Mafia\Irihi.Mafia.csproj" />
<!--    <ProjectReference Include="..\Irihi.Mafia.Themes.TDesign.Icons\Irihi.Mafia.Themes.TDesign.Icons.csproj" />-->
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>
