<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <AvaloniaVersion>12.0.0-preview1</AvaloniaVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)"/>
        <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)"/>
        <PackageVersion Include="Avalonia.iOS" Version="$(AvaloniaVersion)"/>
        <PackageVersion Include="Avalonia.Browser" Version="$(AvaloniaVersion)"/>
        <PackageVersion Include="Avalonia.Android" Version="$(AvaloniaVersion)"/>
        <PackageVersion Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.0-beta2"/>
        <PackageVersion Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.2.0.1"/>

        <PackageVersion Include="Semi.Avalonia" Version="12.0.0-preview1"/>
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0"/>
    </ItemGroup>
</Project>